---
- name: centos | Add key for ELRepo 
  ansible.builtin.rpm_key:
    key: "{{ elrepo_key }}"
    fingerprint: "{{ elrepo_fp }}"
    state: present
  become: true

- name: centos | Add ElRepo for kmod-drbd
  ansible.builtin.yum_repository:
    mirrorlist: "{{ elrepo_url }}"
    name: "elrepo"
    gpgkey: "{{ elrepo_key }}"
    gpgcheck: yes
    description: "ELRepo.org Centos8"
    state: present
  become: true

- name: centos | Installing DRBD packages
  yum:
    name: "{{ drbd_rpm_packages }}"
    state: present
  become: true

- name: centos | Installing Heartbeat Package
  yum:
    name: heartbeat
    state: present
  become: true
  when: drbd_use_heartbeat

- name: centos | Disable usage-count
  lineinfile:
    path: "/etc/drbd.d/global_common.conf"
    regexp: "usage-count yes;"
    line: "   usage-count no;"
    state: present
  become: true
  when: not drbd_usage_count

- name: centos | Default to drbd Protocol C
  lineinfile:
    path: "/etc/drbd.d/global_common.conf"
    regexp: "# protocol timeout max-epoch-size max-buffers"
    line: "   protocol C;"
    state: present
  become: true
